// Print function for the detailed table (must be at top-level, not inside render/JSX)
export function printDetailedTable(students, subjects, grade, section, className) {
  const tableHtml = `
    <div style='margin:32px auto;max-width:1200px;font-family:sans-serif;'>
      <h2 style='text-align:center;font-size:2rem;font-weight:700;color:#1a237e;margin-bottom:8px;'>Sawla International School</h2>
      <h3 style='text-align:center;font-size:1.1rem;font-weight:500;color:#333;margin-bottom:24px;'>Detailed Student Summary</h3>
      <div style='margin-bottom:16px;font-size:1rem;'><b>Grade:</b> ${grade} &nbsp; <b>Section:</b> ${section} &nbsp; <b>Class:</b> ${className}</div>
      <table style='width:100%;border-collapse:collapse;font-size:0.98rem;'>
        <thead>
          <tr style='background:#e3edfa;'>
            <th style='padding:8px 10px;border:1px solid #bcd;'>Student</th>
            <th style='padding:8px 10px;border:1px solid #bcd;'>Email</th>
            ${subjects.map(s => `<th style='padding:8px 10px;border:1px solid #bcd;'>${s}</th>`).join('')}
            <th style='padding:8px 10px;border:1px solid #bcd;'>Total Score</th>
            <th style='padding:8px 10px;border:1px solid #bcd;'>Average (%)</th>
            <th style='padding:8px 10px;border:1px solid #bcd;'>Rank</th>
          </tr>
        </thead>
        <tbody>
          ${students.map(student => `
            <tr>
              <td style='padding:6px 8px;border:1px solid #e0e0e0;'>${student.firstName} ${student.lastName}</td>
              <td style='padding:6px 8px;border:1px solid #e0e0e0;'>${student.email}</td>
              ${subjects.map(subject => {
                const subj = student.subjectMap[subject];
                return `<td style='padding:6px 8px;border:1px solid #e0e0e0;text-align:center;'>${subj ? `${subj.totalEarned} / ${subj.totalPossible}` : '-'}</td>`;
              }).join('')}
              <td style='padding:6px 8px;border:1px solid #e0e0e0;text-align:center;'>${student.totalEarned} / ${student.totalPossible}</td>
              <td style='padding:6px 8px;border:1px solid #e0e0e0;text-align:center;'>${student.avg.toFixed(1)}%</td>
              <td style='padding:6px 8px;border:1px solid #e0e0e0;text-align:center;'>${student.rank}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>
      <div style='margin-top:32px;text-align:center;font-size:12px;color:#888;'>Generated by Sawla SMIS</div>
    </div>
  `;
  const printWindow = window.open('', '', 'width=1200,height=900');
  if (!printWindow) return;
  printWindow.document.write(`
    <html><head><title>Detailed Student Summary</title>
    <style>
      @media print { body { background: #fff !important; } }
    </style>
    </head><body style='background:#f5f7fa;font-family:sans-serif;'>
      ${tableHtml}
      <script>window.onload = function() { window.print(); }</script>
    </body></html>
  `);
  printWindow.document.close();
}
